// Markdown renderer tests: vectors generated by kramdown (test/vectors.rb)

struct MdVector {
    Str in;
    Str want;
};

static MdVector mdvectors[] = {
#include "vectors.inc"
};

// Highlighting is not part of the vectors: drop spans inside code blocks.
static Str unhighlight(Arena *a, Str s)
{
    Buf b(a, s.len);
    b32 code = 0;
    for (iz i = 0; i < s.len;) {
        Str rest = cuthead(s, i);
        if (startswith(rest, "<pre class=\"highlight\"><code>")) {
            code = 1;
        } else if (startswith(rest, "</code></pre>")) {
            code = 0;
        } else if (code && startswith(rest, "<span")) {
            for (; i<s.len && s[i]!='>'; i++) {}
            i++;
            continue;
        } else if (code && startswith(rest, "</span>")) {
            i += 7;
            continue;
        }
        putbyte(&b, s[i++]);
    }
    return finish(&b);
}

static void test_markdown(Test *t)
{
    for (iz i = 0; i < countof(mdvectors); i++) {
        // The log grows in the same arena object as the output
        Arena perm    = t->perm;
        perm.end      = perm.beg + (perm.end - perm.beg)/2;
        Arena scratch = t->perm;
        scratch.beg   = perm.end;
        Log log = {};
        log.buf = Buf(&perm, 1<<12);
        Markdown md = markdown(mdvectors[i].in, "vector", 1, &perm, scratch, &log);

        Buf name(&perm, 64);
        print(&name, "markdown vector ");
        print(&name, (i64)i);
        print(&name, ": ");
        print(&name, mdvectors[i].in);
        expect(t, finish(&name), unhighlight(&perm, md.html), mdvectors[i].want);
    }

    // Excerpts end at a top-level <!--more-->, else at the first blank line
    Arena a = t->perm;
    Log log = {};
    log.buf = Buf(&a, 1<<12);
    Arena scratch = a;
    scratch.beg += (a.end - a.beg)/2;
    a.end = scratch.beg;
    Markdown md = markdown("A\nB\n\nC\n", "", 1, &a, scratch, &log);
    expect(t, "excerpt blank", takehead(md.html, md.excerpt), "<p>A\nB</p>\n");
    md = markdown("A\n\nB\n\n<!--more-->\n\nC\n", "", 1, &a, scratch, &log);
    expect(t, "excerpt more", takehead(md.html, md.excerpt), "<p>A</p>\n\n<p>B</p>\n\n");
    md = markdown("A\n", "", 1, &a, scratch, &log);
    expect(t, "excerpt whole", takehead(md.html, md.excerpt), "<p>A</p>\n");
    md = markdown("A `<!--more-->`\n\nB\n\n<!--more-->\n", "", 1, &a, scratch, &log);
    expect(t, "excerpt code", takehead(md.html, md.excerpt),
           "<p>A <code>&lt;!--more--&gt;</code></p>\n\n<p>B</p>\n\n");
    md = markdown("> A\n>\n> <!--more-->\n\nB\n", "", 1, &a, scratch, &log);
    expect(t, "excerpt nested", takehead(md.html, md.excerpt),
           "<blockquote>\n  <p>A</p>\n\n  <!--more-->\n</blockquote>\n");

    // Syntax that kramdown would parse differently is reported (these
    // were checked against kramdown)
    static struct { Str in; Str want; } warnings[] = {
        {"a | b\n",                "tables are not supported"},
        {"<b>x</b> | y\n",         "tables are not supported"},
        {"`|` and <kbd>|</kbd>\n", ""},
        {"a|b\nc\n",               ""},
        {"a\n: b\n",               "definition lists are not supported"},
        {"x\n\n: b\n",             "definition lists are not supported"},
        {"* x\n\n: b\n",           ""},
        {"$$x$$\n",                "math blocks are not supported"},
        {"$$|\n",                  "tables are not supported"},
        {"[^a]: b\n",              "footnotes are not supported"},
        {"[^]: b\n",               ""},
        {"<div><p markdown=\"1\">a</p></div>\n", "the markdown attribute is not supported"},
    };
    for (iz i = 0; i < countof(warnings); i++) {
        Arena perm    = t->perm;
        perm.end      = perm.beg + (perm.end - perm.beg)/2;
        Arena scratch = t->perm;
        scratch.beg   = perm.end;
        Log log = {};
        log.buf = Buf(&perm, 1<<12);
        markdown(warnings[i].in, "w", 1, &perm, scratch, &log);
        Str got  = finish(&log.buf);
        Str want = warnings[i].want;
        if (want.len && find(got, want)>=0) {
            got = want;
        }
        Buf name(&perm, 64);
        print(&name, "markdown warning: ");
        print(&name, warnings[i].in);
        expect(t, finish(&name), got, want);
    }

    // Deep nesting renders as text, bounding recursion
    Arena perm    = t->perm;
    perm.end      = perm.beg + (perm.end - perm.beg)/2;
    scratch       = t->perm;
    scratch.beg   = perm.end;
    log     = {};
    log.buf = Buf(&perm, 1<<12);
    Buf deep(&scratch, 1<<12);
    for (i32 i = 0; i < 2*MAXDEPTH; i++) {
        print(&deep, "> <span>");
    }
    markdown(finish(&deep), "w", 1, &perm, scratch, &log);
    Str got  = finish(&log.buf);
    Str want = "pathological nesting";
    expect(t, "markdown deep nesting", find(got, want)>=0 ? want : got, want);
}
